/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPatientForm.java
 *
 * Created on 08/08/2010, 12:20:39 PM
 */

package patientwaitinglist;

/**
 *
 * @author Alex
 */
public class AddPatientForm extends javax.swing.JDialog {

    /** Creates new form AddPatientForm */
    public AddPatientForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstNameLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        TCPLabel = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        SurnameField = new javax.swing.JTextField();
        TCPField = new javax.swing.JTextField();
        DateOfDiagnosisLabel = new javax.swing.JLabel();
        DiagnosisDayField = new javax.swing.JTextField();
        DiagnosisMonthField = new javax.swing.JTextField();
        DiagnosisYearField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        GroupComboBox = new javax.swing.JComboBox();
        CancelButton = new javax.swing.JButton();
        AddPatientButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(patientwaitinglist.PatientWaitingListApp.class).getContext().getResourceMap(AddPatientForm.class);
        FirstNameLabel.setText(resourceMap.getString("FirstNameLabel.text")); // NOI18N
        FirstNameLabel.setName("FirstNameLabel"); // NOI18N

        SurnameLabel.setText(resourceMap.getString("SurnameLabel.text")); // NOI18N
        SurnameLabel.setName("SurnameLabel"); // NOI18N

        TCPLabel.setText(resourceMap.getString("TCPLabel.text")); // NOI18N
        TCPLabel.setName("TCPLabel"); // NOI18N

        FirstNameField.setText(resourceMap.getString("FirstNameField.text")); // NOI18N
        FirstNameField.setName("FirstNameField"); // NOI18N

        SurnameField.setText(resourceMap.getString("SurnameField.text")); // NOI18N
        SurnameField.setName("SurnameField"); // NOI18N

        TCPField.setText(resourceMap.getString("TCPField.text")); // NOI18N
        TCPField.setName("TCPField"); // NOI18N

        DateOfDiagnosisLabel.setText(resourceMap.getString("DateOfDiagnosisLabel.text")); // NOI18N
        DateOfDiagnosisLabel.setName("DateOfDiagnosisLabel"); // NOI18N

        DiagnosisDayField.setText(resourceMap.getString("DiagnosisDayField.text")); // NOI18N
        DiagnosisDayField.setName("DiagnosisDayField"); // NOI18N

        DiagnosisMonthField.setText(resourceMap.getString("DiagnosisMonthField.text")); // NOI18N
        DiagnosisMonthField.setName("DiagnosisMonthField"); // NOI18N

        DiagnosisYearField.setText(resourceMap.getString("DiagnosisYearField.text")); // NOI18N
        DiagnosisYearField.setName("DiagnosisYearField"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        GroupComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GroupComboBox.setName("GroupComboBox"); // NOI18N

        CancelButton.setText(resourceMap.getString("CancelButton.text")); // NOI18N
        CancelButton.setName("CancelButton"); // NOI18N

        AddPatientButton.setText(resourceMap.getString("AddPatientButton.text")); // NOI18N
        AddPatientButton.setName("AddPatientButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GroupComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FirstNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(TCPLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCPField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AddPatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelButton))
                            .addComponent(DateOfDiagnosisLabel)
                            .addComponent(SurnameLabel)
                            .addComponent(SurnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DiagnosisDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiagnosisMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiagnosisYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(SurnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCPLabel)
                    .addComponent(DateOfDiagnosisLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiagnosisDayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiagnosisMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiagnosisYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GroupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(AddPatientButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddPatientForm dialog = new AddPatientForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel DateOfDiagnosisLabel;
    private javax.swing.JTextField DiagnosisDayField;
    private javax.swing.JTextField DiagnosisMonthField;
    private javax.swing.JTextField DiagnosisYearField;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JComboBox GroupComboBox;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JTextField TCPField;
    private javax.swing.JLabel TCPLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
